//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation_H
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chambre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chambre()
        {
            this.OccupChambres = new HashSet<OccupChambre>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int idChambre { get; set; }
        public string nomChambre { get; set; }
        public string etat { get; set; }
        public int typeChambre { get; set; }
        public Nullable<decimal> prix_Ch { get; set; }
    
        public virtual TypeChambre TypeChambre1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OccupChambre> OccupChambres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
