//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation_H
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande_service
    {
        public int idServiceDemander { get; set; }
        public Nullable<int> reservation { get; set; }
        public int service { get; set; }
        public System.DateTime dateDemande { get; set; }
    
        public virtual Reservation Reservation1 { get; set; }
        public virtual Service Service1 { get; set; }
    }
}
