//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation_H
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Paiment
    {
        public int idDetail { get; set; }
        public Nullable<int> Facture { get; set; }
        public Nullable<decimal> montantD { get; set; }
        public Nullable<System.DateTime> datePayement { get; set; }
        public Nullable<int> modePayment { get; set; }
        public string detailModePaiment { get; set; }
    
        public virtual Facture Facture1 { get; set; }
        public virtual Mode_Payment Mode_Payment { get; set; }
    }
}
