//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation_H
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class reservation_hotelEntities : DbContext
    {
        public reservation_hotelEntities()
            : base("name=reservation_hotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chambre> Chambres { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Demande_service> Demande_service { get; set; }
        public virtual DbSet<Detail_Paiment> Detail_Paiment { get; set; }
        public virtual DbSet<Facture> Factures { get; set; }
        public virtual DbSet<Mode_Payment> Mode_Payment { get; set; }
        public virtual DbSet<OccupChambre> OccupChambres { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<TypeChambre> TypeChambres { get; set; }
    }
}
