//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation_H
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupChambre
    {
        public int idOccupChambre { get; set; }
        public Nullable<int> reservation { get; set; }
        public Nullable<int> chambre { get; set; }
        public Nullable<System.DateTime> dateOccup { get; set; }
        public Nullable<System.DateTime> dateDispo { get; set; }
        public string typeO { get; set; }
    
        public virtual Chambre Chambre1 { get; set; }
        public virtual Reservation Reservation1 { get; set; }
    }
}
