//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation_H
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Demande_service = new HashSet<Demande_service>();
            this.Factures = new HashSet<Facture>();
            this.OccupChambres = new HashSet<OccupChambre>();
        }
    
        public int idReservation { get; set; }
        public System.DateTime dateReservation { get; set; }
        public System.DateTime dateArrive { get; set; }
        public System.DateTime dateDepart { get; set; }
        public int client { get; set; }
        public Nullable<int> chambre { get; set; }
        public string typeReservation { get; set; }
    
        public virtual Chambre Chambre1 { get; set; }
        public virtual Client Client1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demande_service> Demande_service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facture> Factures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OccupChambre> OccupChambres { get; set; }
    }
}
